name: bundle-python-embed-venv

on: push

jobs:
  build-distro:
    name: Bundle Windows Embeddable Python with pip and virtualenv
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Run Bundle script
        run: .\Bundle-Python.ps1 -PythonVersion "3.7.9"
        shell: pwsh
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: python-3.7.9-embed-amd64-venv
          path: python/
